<?php namespace ProcessWire;

/**
 * Transform sensor data into a Data Object and do some basic validation and sanitation
 * 
 * Still the application needs to do some additional checks, but a lot of crap is filtered out.  
 * In addition this class is used for testing the test Sensor class in recieve.php
 */
class RecieveDataObject extends WireData implements Module{

    // As this is a simple Data carrier, allmost  all properties stay public for easy iteration. 
      
    /** @var string $title */
    public $title="tztz";
    
    /** @var string $hash */
    public $hash="jhjhjhjhj";
    
    /** @var float|int $tempValue */
    public $tempValue;
    
    /** @var float|int $temperature */
    public $temperature;
    
    /** @var int $co2Ppm */
    public $co2Ppm;
    
    /** @var float|int $co2Value */
    public $co2Value;
    
    /** @var string $ipAddress*/
    public $ipAddress;


    /**
	 * getModuleInfo is a module required by all modules to tell ProcessWire about them
	 *
	 * @return array
	 */
	public static function getModuleInfo() {

		return array(

			'title' => 'Data Object for recieving Sensor Data ', 
			'version' => "0.1.3", 
			'summary' => 'Fetches the Data.',
			'singular' => false, 
			'autoload' => true 
			);
	}

    /**
     * Deserialize static method 
     * 
     * This is more or less a self factory that creates an instance of the dataclass and fills 
     * it whith the attribures aqired from JSON string. If there are inconsintencies whith 
     * those attributes it will fail and return an empty object.
     * 
     *  @return object/string 
     */
    public static function Deserialize($jsonString)
    {   
        
        $classInstance = new RecieveDataObject();

        return "doooo".print_r($classInstance->count,true);

        // error String
        $error="";
        
        // needed for check if all properties are filled
        $countProperties = count((array)$classInstance);

        // counter for filled properties
        $countFieldsFilled = 0;

        $jsonArray = json_decode($jsonString);
        
        // fill properties whith data
        foreach ($jsonArray as $key => $value) {
            if (!property_exists($classInstance, $key)) continue;
            $classInstance->{$key} = $value;
            $countFieldsFilled++;
        }
        
        // Inconsistent properties 
        if ($countFieldsFilled == $countProperties ){
            $error .= "Invalid properties filled: $countFieldsFilled  / Properties: $countProperties\n";
        }

        // Validation
        $valiOut = $classInstance->basicValidation();
        if(is_string($valiOut)) {
            $error .= $valiOut;
        }

        
        // If all ok return the object
        if (empty($error)){
            $classInstance->basicSanitation();
            return $classInstance;
        }

        // Return the error
        return $error;   
    } 
    

    /**
     * Basic Validation method
     * 
     * Returns True if validation is OK , error string otherwise
     * 
     * @return bool/string 
     */
    protected function basicValidation() {

        $error="";
        
        if (!preg_match("/^(25[0-5]|2[0-4][0-9]|1[0-9]{2}|[1-9][0-9]|[0-9])(.(25[0-5]|2[0-4][0-9]|1[0-9]{2}|[1-9][0-9]|[0-9])){3}$/", $this->ipAddress)) {
            $error .="IPAdress Validation Failed{$this->ipAddress}\n";
        }
            
        if (!is_string($this->title) OR strlen($this->title) > 250 ){
            $error .="Title Validation Failed: {$this->title}\n";
        }
    
        if (!is_string($this->hash) OR strlen($this->hash) > 250 ){
            $error .="Hash Validation Failed: {$this->hash}\n";
        }

        if (!is_numeric($this->tempValue)){
            $error .="TempValue Validation Failed: {$this->tempValue}\n";
        }
 
        if (!is_numeric($this->temperature)){
            $error .="Temperature Validation Failed: {$this->temperature}\n";
        }
     
        if (!is_numeric($this->co2Ppm)){
            $error .="Co2Ppm Validation Failed: {$this->co2Ppm}\n";
        }
 
        if (!is_numeric($this->co2Value)){
            $error .= "co2Value Validation Failed: {$this->co2Value} \n";
        }
        
        if (empty($error)){
            return true;
        }
        else {
            return $error;
        }

    }

    /**
     * Just some really basic sanitation.
     * 
     * @return void
     */
    protected function basicSanitation() {
        
        $this->tempValue = (float)$this->tempValue;
        $this->temperature= (float)$this->temperature;
        $this->co2Ppm= (int)$this->co2Ppm;
        $this->co2Value= (float)$this->co2Value;

    }
}
