<?php namespace ProcessWire;

/**
 * Redirect on Main page
 *
 * As frontend Pages are not used we simply redirect to backend 
 * and force login as guest.  
 */

class RedirOnMain extends WireData implements Module {

	/**
	 * getModuleInfo is a module required by all modules to tell ProcessWire about them
	 *
	 * @return array
	 *
	 */
	public static function getModuleInfo() {

		return array(

			'title' => 'Redirect if not on an admin page', 
			'version' => "0.1.2", 
			'summary' => 'Redirects and Login as Guest if not on an Admin Page.',
			'singular' => true, 
			'autoload' => true, 
			//'icon' => 'smile-o', 
			);
	}

    public function ready() {
        // Auto Login and Redirect
        if($this->page->template != 'admin') {
            $this->session->forceLogin('dozent'); 
            $this->session->redirect('/processwire');     
        }

    }
	
}
