<?php namespace ProcessWire;

/**
 * Save Room Module
 *
 * Adds hooks to handle all the necessary steps that are needed to 
 * save the Room template
 * 
 * @attention: Please look into SaveSensor.module for more detailed comments.
 */

class SaveTypes extends WireData implements Module {

	/**
	 * getModuleInfo required by module interface
	 * @return array
	 */
	public static function getModuleInfo() {

		return array(
			'title' => 'Save actions for Types template', 
			'version' => "0.1.1", 
			'summary' => 'Simple module to manage save actions on template Types.',
			'singular' => true, 
			'autoload' => true, 
			//'icon' => 'smile-o', 
			);
	}

	/**
	 * Initialize the module
	 */
	public function init() {

		// add a hook after the $pages->save, to issue hook  every time a page is saved
		$this->pages->addHookAfter('saveReady', $this, 'calculateType'); 	
	}

	/**
	 * Hook for saving template Room 
	 * 
	 * @param HookEvent $event
	 */
	public function calculateType($event) {
		$page = $event->arguments(0);
        $settings= wire('pages')->get('/settings/');

		// return if not relevant
		if($page->template->name !== 'Type') return;

        // ////////////////////
        // set default values 

        // ////////////////////
        // Do Checks

        // ////////////////////
		// calculate fields
        
        //@TODO Add a check to avoid turning off types that have active Sensors  


	}


	
	
}
