<?php namespace ProcessWire;

/**
 * Save Settings Module
 *
 * Adds hooks to handle all the necessary steps that are needed to 
 * save the Settings template
 *
 * This module gives a place to handle things that happen when global 
 * application settings are changed. 
 * 
 * @attention: Please look into SaveSensor.module for more detailed comments.
 */

class SaveSettings extends WireData implements Module {

	/**
	 * getModuleInfo required by module interface
	 * @return array
	 */
	public static function getModuleInfo() {

		return array(
			'title' => 'Save actions for Settings template', 
			'version' => "0.1.1", 
			'summary' => 'Simple module to manage save actions on template Settings.',
			'singular' => true, 
			'autoload' => true, 
			//'icon' => 'smile-o', 
			);
	}

	/**
	 * Initialize the module
	 */
	public function init() {

		// add a hook after the $pages->save, to issue hook  every time a page is saved
		$this->pages->addHookAfter('saveReady', $this, 'calculateSettings'); 	
	}

	/**
	 * Hook for saving template Room 
	 * 
	 * @param HookEvent $event
	 */
	public function calculateSettings($event) {
		$page = $event->arguments(0);

		// return if not relevant
		if($page->template->name !== 'Settings') return;

        // ////////////////////
        // set default values 

        // ////////////////////
        // Do Checks

        // ////////////////////
		// calculate fields
   	
	}


	
	
}
