<?php namespace ProcessWire;

/**
 * SendOutWarlert Module
 *
 * Takes Care of sending out Messages for Co2 Alerts and Warnings 
 * Simply extend the send method whith additional senders. 
 * 
 * 
 */

class SendOutWarlert extends WireData implements Module {

	/**
	 * getModuleInfo required by module interface
	 * @return array
	 */
	public static function getModuleInfo() {

		return array(
			'title' => 'Send out alerts and warnings', 
			'version' => "0.1.1", 
			'summary' => 'Takes care of sending out all alerts and warnings.',
			'singular' => false, 
			'autoload' => false, 
			//'icon' => 'smile-o', 
			);
	}

	/**
	 * Initialize the module
     * can be used as a substitute for _construct, but with module settings activated 
	 */
	public function init() {
        // No hooks today
	}

    ///////////////////////////////////
    // Additional Class Vars

    /** @var WireObject $room Room to handle*/
    protected $room;

    /** @var array $targets Targets to send to.*/
    protected $targets;
    
    /** @var string $text Text to send*/
    protected $text = "";

    /** @var string $level use "warn" or "alert" */
    protected $level = "warn"; 
 
    ///////////////////////////////////
    // Collectiion of Setters 
    
    /**
     * @param WireObject $room
     * @param string $text
     * @param string $level
     * @return void
     */
    public function send($text, $room, $level) {
            $this->room  = $room;
            $this->level = $level;
            $this->text  = $text;
            $this->findTargets();
            if (!empty($targets))
                $this->sendAll();
            else 
                $this->error("Cannot send Warning no targets defined for Rooom: { $room->title}");
    }
 

 	/**
	 * Find the Targets to send to 
	 */
	protected function findTargets() {
         	
	}
    /**
	 * Send to all available targets 
	 */
	protected function sendAll() {

         	
	}


	
	
}
