<?php namespace ProcessWire;

/**
 * Sensor data reciever module/page
 *
 * This module creates an URL hook to recieve data from different sensors. 
 * The Hook creates a page routing that pipes all incomming traffic to that URL to this module.   
 */

class SensorRecieveData extends WireData implements Module {

	/**
	 * getModuleInfo is a module required by all modules to tell ProcessWire about them
	 *
	 * @return array
	 *
	 */
	public static function getModuleInfo() {

		return array(

			'title' => 'Sensor data reciever module/page', 
			'version' => "0.1.2", 
			'summary' => 'URL Hook whith funktionality to recieve sensor data.',
			'singular' => true, 
			'autoload' => true
			);
	}

    /**  
     *  This little hook does all the webpage routing to the recieve method.
     *  
     *  Init comes before ready so this comes before RedirOnMain  
    */
    public function Init() {
		$this->pages->addHook('/reciever/', $this, 'recieveData'); 	
    }

    /**
     * Recieve method get called when Hook is triggered
     */
    public function recieveData($event) {

        
        
        // Fetch JSON Data
        $jsonString = $this->input->post('jsonData'); 

        // Json string kommt hier an 
        //return print_r($this->input->post('jsonData'),true);

        // Nothing to process so end it here
        if (empty($jsonString)) {
            return "!! jsonData not found or empty !!";
        }
		
        $myData = dataObject::Deserialize($jsonString);

        // Data was completely invalid return the error if debug is on 
        if (is_string($myData)) {
            if ($this->config->debug){
                return print_r($myData,true);
            }
            else {
                return "!! Failed !!";
            }
        }
        return "\nSUCCESS\n\n". print_r($myData,true);

        // From here we create and validate for the Data Page 

        

	}
	
}


/**
 * Transform sensor data into a Data Object and do some basic validation and sanitation
 * 
 * Still the application needs to do some checks, but a lot of crap is filtered out.  
 * In addition this class is used for testing the test Sensor class in recieve.php
 */
class dataObject {
      
    /** @var string $title */
    public $title;
    
    /** @var string $hash */
    public $hash;
    
    /** @var float|int $tempValue */
    public $tempValue;
    
    /** @var float|int $temperature */
    public $temperature;
    
    /** @var int $co2Ppm */
    public $co2Ppm;
    
    /** @var float|int $co2Value */
    public $co2Value;
    
    /** @var string $ipAddress*/
    public $ipAddress;


    /**
     * Deserialize static method 
     * 
     * This is more or less a self factory that creates an instance of the dataclass and fills 
     * it whith the attribures aqired from JSON string. If there are inconsintencies whith 
     * those attributes it will fail and return an empty object.
     * 
     *  @return object/false 
     */
    public static function Deserialize($jsonString)
    {
        $classInstance = new DataObject();
        
        // needed for check if all are filled
        $cProperties = count((array)$classInstance);

        $jsonArray = json_decode($jsonString);
        
        $cFilled = 0;

        foreach ($jsonArray as $key => $value) {
            if (!property_exists($classInstance, $key)) continue;

            $classInstance->{$key} = $value;
            $cFilled++;
        }
        
        // All properties have benn filled?
        if ($cFilled == $cProperties ){
            // Validation ok so return Object
            if ($classInstance->basicValidation()){
                // but some basic sanitation first
                $classInstance->basicSanitation();
                return $classInstance;
            }
            else {
                echo"Basic Validation failed!\n"; 
            }

        } 
        else {
            echo"Invalid properties filled: $cFilled  / Properties: $cProperties\n"; 
        }

        // concerning PHP manual its better to use both
        $classInstance = NULL;
        unset($classInstance);

        return (object)[];   // Returns empty Object
    } 
    

    /**
     * Basic Validation class 
     * 
     * Returns True if validation is OK , false otherwise
     * 
     * @return bool 
     */
    protected function basicValidation() {
        
        if (!preg_match("/^(25[0-5]|2[0-4][0-9]|1[0-9]{2}|[1-9][0-9]|[0-9])(.(25[0-5]|2[0-4][0-9]|1[0-9]{2}|[1-9][0-9]|[0-9])){3}$/", $this->ipAddress)) {
            echo("IPAdress Validation Failed{$this->ipAddress}\n");
            return false;
        }
            
        if (!is_string($this->title) OR strlen($this->title) > 250 ){
            echo("Title Validation Failed: {$this->title}\n");
            return false;
        }
    
        if (!is_string($this->hash) OR strlen($this->hash) > 250 ){
            echo("Hash Validation Failed: {$this->hash}\n");
            return false;
        }

        if (!is_numeric($this->tempValue)){
            echo("TempValue Validation Failed: {$this->tempValue}\n");
            return false;
        }
 
        if (!is_numeric($this->temperature)){
            echo("Temperature Validation Failed: {$this->temperature}\n");
            return false;
        }
     
        if (!is_numeric($this->co2Ppm)){
            echo("Co2Ppm Validation Failed: {$this->co2Ppm}\n");
            return false;
        }
 
        if (!is_numeric($this->co2Value)){
            echo("co2Value Validation Failed: {$this->co2Value} \n");
            return false;
        }
        
        return true;

    }

    /**
     * Just some really basic sanitation.
     * 
     * @return void
     */
    protected function basicSanitation() {
        
        $this->tempValue = (float)$this->tempValue;
        $this->temperature= (float)$this->temperature;
        $this->co2Ppm= (int)$this->co2Ppm;
        $this->co2Value= (float)$this->co2Value;

    }
}